# Generated by Django 3.0.2 on 2020-01-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'Books'},
        ),
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
