# Generated by Django 3.0.2 on 2020-01-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200111_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='edition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
