# Generated by Django 3.0.2 on 2020-01-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_books_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='views',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
