# Generated by Django 3.0.2 on 2020-01-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_books_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_file',
            field=models.FileField(null=True, upload_to='C:\\django-projects\\shamela\\media'),
        ),
    ]
