# Generated by Django 3.0.2 on 2020-01-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_books_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='C:\\django-projects\\shamela\\media'),
        ),
    ]
