# Generated by Django 3.0.2 on 2020-01-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200131_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
