# Generated by Django 3.0.2 on 2020-01-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200131_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='books/%Y/%m/%d'),
        ),
    ]
