# Generated by Django 3.0.2 on 2020-01-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200131_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_file_m',
            field=models.FileField(blank=True, null=True, upload_to='books_m/%Y/%m/%d'),
        ),
    ]
