# Generated by Django 3.0.2 on 2020-01-31 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_books_book_file_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_file_m',
        ),
    ]
