# Generated by Django 3.0.2 on 2020-02-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_books_book_file_m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='views',
            field=models.BigIntegerField(default=0),
        ),
    ]
