# Generated by Django 3.0.2 on 2020-02-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200203_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
