# Generated by Django 3.0.2 on 2020-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userbooks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbooks',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
