# Generated by Django 3.0.2 on 2020-02-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_userbooks_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='phone_book_file',
            field=models.FileField(blank=True, null=True, upload_to='phone_books/%Y/%m/%d'),
        ),
    ]
