# Generated by Django 3.0.2 on 2020-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_books_phone_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbooks',
            name='status',
            field=models.CharField(choices=[('1', 'Approved'), ('0', 'Pending')], default='0', max_length=1),
        ),
    ]
